### ISSUE TITLE
Can't send Bitclout anymore

### ISSUE THREAD

**Issue by marnimelrose** [bitclout/frontend#384]
It is asking me to purchase a creator coin before I can send $Clout. I have no idea what that means since I already have one. Here is the error
![Window_and_Send__CLOUT_-_BitClout](https://user-images.githubusercontent.com/83539591/129266978-f0f4253a-9729-49f5-9f25-e33548d4fa19.png)

**Comment by marnimelrose** [comment]
By the way, it worked from another account, just not mine.

**Comment by marnimelrose** [comment]
This happened after I verified and it does not happen on any of my accounts that at unverified.

**Comment by AdityaChaudhary0005** [comment]
have seen some similar complaints from users who got $10 from merlin

**Comment by lazynina** [comment]
@marnimelrose if you buy any amount of any creator coin (even as little as penny), this will go away.

After completing the verification, we want users to not immediately send away their coins (helps prevent bots), so we require them to purchase even a tiny amount of creator coins in order to allow Basic transfers.  The pattern we saw from bots was that they will get their free money and immediately send it to an account accumulating sign-up bonuses.

**Comment by marnimelrose** [comment]
As @AdityaChaudhary0005 mentioned it is not creator coins purchased, I have hundreds of dollars of creator coins in my wallet.

**Comment by lazynina** [comment]
You must purchase creator coins after [this update](https://github.com/bitclout/backend/pull/96) was deployed. We only recently added this in and it is forward looking, so it doesn't consider what you've done in the past unfortunately. Purchasing ANY amount of any creator (even yourself and even fractions of a penny) will flip the `HasPurchased` attribute of your user metdata to be true and you will be able to perform basic transfers again.

**Comment by marnimelrose** [comment]
Ah ok thanks!

**Comment by lazynina** [comment]
Thanks @marnimelrose - I'm going to close this issue now. If you have further concerns related to this issue, please re-open and provide further details.
